CREATE TABLE IF NOT EXISTS hr_personnel_asset (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  personnel_id BIGINT NOT NULL COMMENT '人员ID',
  asset_name VARCHAR(50) NOT NULL COMMENT '资产名称',
  asset_code VARCHAR(50) COMMENT '资产编号',
  receive_date DATE COMMENT '领用日期',
  return_date DATE COMMENT '归还日期',
  status TINYINT DEFAULT 1 COMMENT '状态：1在用 2已归还',
  remark VARCHAR(200) COMMENT '备注',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='人员资产表';

CREATE TABLE IF NOT EXISTS hr_personnel_salary (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  personnel_id BIGINT NOT NULL COMMENT '人员ID',
  salary_type VARCHAR(20) COMMENT '类型：DAILY日薪 MONTHLY月薪',
  amount DECIMAL(10,2) NOT NULL COMMENT '金额',
  effective_date DATE NOT NULL COMMENT '生效日期',
  reason VARCHAR(100) COMMENT '变更原因',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='工资变更记录表';

CREATE TABLE IF NOT EXISTS hr_project_milestone (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  project_id BIGINT NOT NULL COMMENT '项目ID',
  milestone_name VARCHAR(100) NOT NULL COMMENT '里程碑名称',
  plan_date DATE COMMENT '计划日期',
  actual_date DATE COMMENT '实际日期',
  amount DECIMAL(10,2) COMMENT '付款金额',
  status TINYINT DEFAULT 0 COMMENT '状态：0待付款 1已付款',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='项目里程碑表';
